--- 
title: "The influence of LiDAR acquisition time lag on bird species distribution models"
author: "Brendan Casey"
supervisor: "Erin Bayne"
site: bookdown::bookdown_site
output: 
    bookdown::gitbook:
      split_by: "section"
      split_bib: no
bibliography: ../../../zotero/library1.bib   
citation-style: ../../MendeleyBib/CitationStyles/ecology.csl
documentclass: book
link-citations: true
github-repo: https://github.com/bgcasey/chapter_1
description: "This is document walks through the analyses I performed for this research."


---


# Overview


```{r GlobalOptions, echo=FALSE}
options(bookdown.render.file_scope = FALSE, knitr.duplicate.label = "allow") 
knitr::opts_chunk$set(cache.path = "5_cache/")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```



```{css, echo=FALSE}
# set max height of code chunks using the following css styling

pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 500px;
}
```


```{r echo=FALSE, out.width = '100%'}
library(kableExtra)
library(knitr)
```




 



# Methods overview

```{r echo=FALSE, out.width = '100%'}
```



# Gather and prepare data

## Bird data

```{r child = '1_code/rNotebooks/1_setup/1_bird_data.Rmd'}
```


## Classified landcover data

```{r child = '1_code/rNotebooks/1_setup/2_landcover_data.Rmd'}
```


## LiDAR data

```{r child = '1_code/rNotebooks/1_setup/3_lidar_data.Rmd'}
```


## Combine and filter

```{r child = '1_code/rNotebooks/1_setup/4_combine_data.Rmd'}
```

## Combine and filter

```{r child = '1_code/rNotebooks/1_setup/4_combine_data.Rmd'}
```

## Prepare Data for SDMs
```{r child = '1_code/rNotebooks/1_setup/5_format_and_filter.Rmd'}
```


# SDMs


```{r child = '1_code/rNotebooks/2_sdms/sdm_AMRE.Rmd'}
```

```{r child = '1_code/rNotebooks/2_sdms/sdm_BTNW.Rmd'}
```

```{r child = '1_code/rNotebooks/2_sdms/sdm_MOWA.Rmd'}
```

```{r child = '1_code/rNotebooks/2_sdms/sdm_SWTH.Rmd'}
```

```{r child = '1_code/rNotebooks/2_sdms/sdm_WIWR.Rmd'}
```

```{r child = '1_code/rNotebooks/2_sdms/sdm_WTSP.Rmd'}
```

```{r child = '1_code/rNotebooks/2_sdms/sdm_YBSA.Rmd'}
```




# Compare SDMs accross years

```{r child = '1_code/rNotebooks/3_compare/compare_AMRE.Rmd'}
```

```{r child = '1_code/rNotebooks/3_compare/compare_BTNW.Rmd'}
```

```{r child = '1_code/rNotebooks/3_compare/compare_MOWA.Rmd'}
```

```{r child = '1_code/rNotebooks/3_compare/compare_SWTH.Rmd'}
```

```{r child = '1_code/rNotebooks/3_compare/compare_WIWR.Rmd'}
```

```{r child = '1_code/rNotebooks/3_compare/compare_WTSP.Rmd'}
```

```{r child = '1_code/rNotebooks/3_compare/compare_YBSA.Rmd'}
```

# Results summary

```{r child = '1_code/rNotebooks/4_summary/1_summarize_results.Rmd'}
```



# References


<div id="refs"></div>



# Appendix
