## BTNW


```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{css, echo=FALSE}
# set max height of code chunks using the following css styling

pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 500px;
}
```

### Load packages {-}

```{r eval=FALSE, message = FALSE}
library(dplyr)
library(lme4)
library(car)
#library(piecewiseSEM) # for psudo R2
# library(jtools)
# library(MuMIn)
# library(see)
# library(performance)
# library(effects)
# library(DHARMa)
# library(fitdistrplus)
# library(purrr)
# library(webshot)
# library(r2glmm)
```


### Load data {-}

```{r eval=FALSE}
load("2_pipeline/tmp/sdm_d.rData")
d<-sdm_d

#filter to surveys done at the same year as the lidar acquisition

d<-d%>%
  filter(SS_lidar_timelag==0)
```




### Evaluate random effects {-}

```{r eval=FALSE}
BTNW_m0<-glm(BTNW ~ 1, data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude)

BTNW_m1<-lme4::glmer(BTNW ~ 1 + (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude)

BTNW_m2<-lme4::glmer(BTNW ~ 1 + (1|SS) + (1|ss_year), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude)

# # Compare models
anova(BTNW_m1, BTNW_m2)

BTNW_null_ms <- model.sel(BTNW_m2, rank="AIC", extra = c(r2=function(x) round(r.squaredGLMM(x)[1,c(1,2)],3)))

save(BTNW_null_ms, file="2_pipeline/store/models/BTNW_null_ms.rData")
```


#### Build models {-}


##### Evaluate classified landcover variable {-}


```{r eval=FALSE}
cm1<-lme4::glmer(BTNW ~ rast_forest_age  + (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude )

cm2<-lme4::glmer(BTNW ~  LCC4 + (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude )

cm3<-lme4::glmer(BTNW ~  LCC4 + LCC2 + rast_forest_age + Forest_Type + (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude)

# There is not much variation in the factor levels so we'll just stick with rast_forest_age as a precitor. 
```

##### Prelim LiDAR models {-}

```{r eval=FALSE}

#plug in all LiDAR variables
plm1<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+ elev_0pnt15_to_2pnt00_return_proportion+ elev_10pnt00_to_15pnt00_return_proportion+ elev_15pnt00_to_20pnt00_return_proportion+ elev_20pnt00_to_25pnt00_return_proportion+ elev_25pnt00_to_30pnt00_return_proportion+ elev_2pnt00_to_4pnt00_return_proportion+ elev_30pnt00_to_50pnt00_return_proportion+ elev_4pnt00_to_6pnt00_return_proportion+ elev_6pnt00_to_8pnt00_return_proportion+ elev_8pnt00_to_10pnt00_return_proportion + elev_below_0pnt15_return_proportion+ elev_cv+ elev_kurtosis+ elev_maximum + elev_mean+ elev_p05 + elev_p10 + elev_p20 + elev_p25 + elev_p30 + elev_p50 + elev_p60 + elev_p70 + elev_p75 + elev_p80 + elev_p95 + elev_p99 + elev_stddev+ percentage_first_returns_above_2pnt00+ percentage_first_returns_above_mean+ total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 


#Extract variance-covariance matrix for all parameters
library(merDeriv)
merDeriv::vcov.glmerMod(lm1)

#Check variance inflation factors of fixed effects
l_vif<-as.data.frame(vif(lm1))

# Iteratively remove highly correlated variables with VIF > 3 and r >.5 
plm2<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+ elev_0pnt15_to_2pnt00_return_proportion+ elev_10pnt00_to_15pnt00_return_proportion+ elev_15pnt00_to_20pnt00_return_proportion+ elev_20pnt00_to_25pnt00_return_proportion+ elev_25pnt00_to_30pnt00_return_proportion+ elev_2pnt00_to_4pnt00_return_proportion+ elev_30pnt00_to_50pnt00_return_proportion+ elev_4pnt00_to_6pnt00_return_proportion+ elev_6pnt00_to_8pnt00_return_proportion+ elev_8pnt00_to_10pnt00_return_proportion + elev_below_0pnt15_return_proportion+ elev_cv+  elev_maximum + elev_mean+  elev_p50 + elev_p95 + elev_p99 + elev_stddev+ percentage_first_returns_above_2pnt00+ percentage_first_returns_above_mean+ total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 


plm3<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_cv+  elev_maximum + elev_mean+  elev_p50 + elev_p95 + elev_p99 + elev_stddev+ percentage_first_returns_above_2pnt00+ percentage_first_returns_above_mean+ total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 


plm3<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_cv+  elev_maximum + elev_mean+  elev_p50 + elev_p95 + elev_p99 + elev_stddev+ percentage_first_returns_above_2pnt00+ percentage_first_returns_above_mean+ total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 

l_vif<-as.data.frame(vif(lm3))


plm4<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_cv+  elev_maximum +  elev_p50 + elev_p95  + elev_stddev+ percentage_first_returns_above_2pnt00+ percentage_first_returns_above_mean+ total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 

l_vif<-as.data.frame(vif(lm4))


plm5<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_maximum +  elev_p50   + elev_stddev+ percentage_first_returns_above_2pnt00+ percentage_first_returns_above_mean+ total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 

l_vif<-as.data.frame(vif(lm5))

plm6<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_maximum + elev_stddev+ percentage_first_returns_above_2pnt00+ percentage_first_returns_above_mean+ total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 

l_vif<-as.data.frame(vif(lm6))

plm7<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_maximum + elev_stddev+ percentage_first_returns_above_2pnt00 + total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 

l_vif<-as.data.frame(vif(lm7))

plm8<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_maximum + elev_stddev + total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 

l_vif<-as.data.frame(vif(lm8))

###################
#candidates
###################
# rast_forest_age       
# canopy_relief_ratio  
# elev_maximum       
# elev_stddev          
# total_all_returns  


#Try swap out different predictor variables of the same class
plm9<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_p95 + elev_stddev + total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 
l_vif<-as.data.frame(vif(lm9))

plm10<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_maximum + elev_cv + total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 
l_vif2<-as.data.frame(vif(lm10))

plm11<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_maximum + elev_stddev + elev_p50 +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 

plm12<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_p95 + elev_cv + total_all_returns +  (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 
l_vif2<-as.data.frame(vif(lm10))

plm13<-lme4::glmer(BTNW ~ rast_forest_age + canopy_relief_ratio+  elev_maximum + elev_stddev + total_all_returns + elev_p50 + (1|SS), data=d, family = binomial, offset = BTNW_OFF,  na.action = na.exclude ) 
```


**LiDAR candidate variables**
- canopy_relief_ratio  
- elev_maximum       
- elev_stddev          
- total_all_returns  


##### GLM's


``` {eval=FALSE}
vif(lm1)


```



