---
title: "The influence of time-lag between LiDAR and wildlife survey data on species distribution models"
author: Brendan Casey
abstract: |
 LiDAR has the potential to improve bird-habitat models by providing high resolution structural covariates which can give insight into bird-habitat relationships. However, LiDAR acquisitions do not always coincide in time with point count surveys. It is unclear how much this temporal misalignment influence the predictive accuracy of bird-habitat models that use LiDAR derived predictor variables. As disturbance-succession cycles change vegetation structure, eventually LiDAR metrics will no longer reflect ground conditions. Thus the usefulness of LiDAR explanatory variables will degrade. Here, we evaluated how time-lag between LiDAR acquisitions and bird surveys influenced model robustness for early-successional, mature-forest, and forest generalist birds. We found that for species occupying older, more stable forests, a time difference of up to 15 years has only a small impact on the predictive power of LiDAR based bird-habitat models. However, for early-successional birds, our findings suggest that a time difference of 5-13 years between LIDAR and bird data may reduce model performance.
fontsize: 12pt
keywords: one, two, three
linestretch: 1.25
# geometry: "left=4cm, right=3cm, top=2.5cm, bottom=2.5cm"
date: "`r Sys.Date()`"
bibliography: library.bib
link-citations: yes
linenumbers: FALSE
modulolinenumbers: 1
numbersections: true
colorlinks: yes
citecolor: blue
# Use a CSL with `citation_package = "default"`
biblio-style: apalike
csl: https://www.zotero.org/styles/elsevier-harvard
toc: yes 
lof: yes 
lot: yes
geometry: margin=2.54cm
---


```{r setup, include=FALSE}

library(knitr)
library(tinytex)
library(kableExtra)
library(xlsx)


knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, signif = 3,
                      out.extra = "",
                      out.width = "100%",
                      fig.retina = 2,
                      fig.pos = 'htb')

# # move figure files to manuscript directory
# file.copy(from="../images/chapter3_workflow.pdf", to="figures/chapter3_workflow.pdf",
#           overwrite = TRUE, recursive = FALSE,
#           copy.mode = TRUE)
# file.copy(from="../latex_figures/summ_freq_all_c.png", to="figures/summ_freq_all_c.png",
#           overwrite = TRUE, recursive = FALSE,
#           copy.mode = TRUE)
# file.copy(from="../empirical/3_output/figures/r2_plot_c.png", to="figures/r2_plot_c.png",
#           overwrite = TRUE, recursive = FALSE,
#           copy.mode = TRUE)
# file.copy(from="../latex_figures/contrFixed_c.png", to="figures/contrFixed_c.png",
#           overwrite = TRUE, recursive = FALSE,
#           copy.mode = TRUE)
# file.copy(from="../empirical/3_output/maps/studyArea_inset.png", to="figures/studyArea_inset.png",
#           overwrite = TRUE, recursive = FALSE,
#           copy.mode = TRUE)

knitr::read_chunk("code/figures_tables.R")
  
```



```{r child = 'scrivener_manuscript.md'}
```


