```{r setup, include=FALSE, cache=FALSE}
#Set root directory to R project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{css, echo=FALSE}
# set max height of code chunks using the following css styling

pre {
  max-height: 300px;
  overflow-y: auto;
}

pre[class] {
  max-height: 500px;
}
```


# Setup {-}
## Load packages {-}
```{r eval=FALSE}
library(auk)



# resolve namespace conflicts
select <- dplyr::select
projection <- raster::projection

# set random number seed to insure fully repeatable results
set.seed(1)
```






## Load data {-}

```{r}

BAM<-read.csv("../../data/avian_lifeHistory/BAM_avianDatabase/tables/BAM_ss_spp.csv", header = TRUE)
#make copy
b<-BAM 

# rename columns
names(b)[7]<- "x"
names(b)[8]<- "y"

#Change myrtle warbler to yellow-rumped warbler
b$SPECIES[b$SPECIES == "MYWA"] <- "YRWA"


load("2_pipeline/tmp/sdm_d.rData")
d<-sdm_d
```

# filter prior to creating occupancy model data
```{r}
d




d_filtered <- filter(d, 
                         number_observers <= 5,
                         year == max(year))
```

